
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laudry.in;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class pesanan extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    
    public pesanan() {
        initComponents();
        

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnriwayat = new javax.swing.JButton();
        btntransaksibaru = new javax.swing.JButton();
        btnpesanan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtberat = new javax.swing.JTextField();
        jeniscucian = new javax.swing.JComboBox<>();
        txttotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnbatal = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btntransaksi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbpelanggan = new javax.swing.JComboBox<>();
        btndatapelnggan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jButton4.setText("Kembali");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAUNDRY.IN");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnriwayat.setBackground(new java.awt.Color(204, 204, 204));
        btnriwayat.setText("Riwayat Transaksi");
        btnriwayat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, null));
        btnriwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnriwayatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnriwayatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnriwayatMouseExited(evt);
            }
        });
        btnriwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnriwayatActionPerformed(evt);
            }
        });
        getContentPane().add(btnriwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 30));

        btntransaksibaru.setBackground(new java.awt.Color(204, 204, 204));
        btntransaksibaru.setText("Transaksi Baru");
        btntransaksibaru.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, null));
        btntransaksibaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntransaksibaruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntransaksibaruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntransaksibaruMouseExited(evt);
            }
        });
        btntransaksibaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransaksibaruActionPerformed(evt);
            }
        });
        getContentPane().add(btntransaksibaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 30));

        btnpesanan.setBackground(new java.awt.Color(156, 195, 223));
        btnpesanan.setText("Pesanan");
        btnpesanan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, null));
        btnpesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpesananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpesananMouseExited(evt);
            }
        });
        btnpesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesananActionPerformed(evt);
            }
        });
        getContentPane().add(btnpesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PESANAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 150, -1));
        getContentPane().add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 270, 30));
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 180, 30));

        txtberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberatActionPerformed(evt);
            }
        });
        txtberat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtberatKeyReleased(evt);
            }
        });
        getContentPane().add(txtberat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 90, 30));

        jeniscucian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "cuci basah", "cuci kering", "cuci setrika" }));
        jeniscucian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeniscucianActionPerformed(evt);
            }
        });
        getContentPane().add(jeniscucian, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 180, 30));

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 270, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Berat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Total Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Bayar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 130, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Jenis Cucian");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 130, 30));

        btnbatal.setBackground(new java.awt.Color(255, 51, 51));
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 80, -1));

        btnsimpan.setBackground(new java.awt.Color(102, 255, 102));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 80, -1));

        btntransaksi.setBackground(new java.awt.Color(255, 153, 51));
        btntransaksi.setText("Transaksi");
        btntransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btntransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 90, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Kg");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 60, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nama Pelanggan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 30));

        cmbpelanggan.setModel(cmbpelanggan.getModel());
        cmbpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(cmbpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 180, 30));

        btndatapelnggan.setText("Data ");
        btndatapelnggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatapelngganActionPerformed(evt);
            }
        });
        getContentPane().add(btndatapelnggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesain/Untitled.png"))); // NOI18N
        jLabel1.setDoubleBuffered(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseWheelMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnriwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnriwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnriwayatActionPerformed

    private void btnriwayatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnriwayatMouseEntered
        // TODO add your handling code here:
        btnriwayat.setBackground(new Color(156,195,223));
    }//GEN-LAST:event_btnriwayatMouseEntered

    private void btntransaksibaruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransaksibaruMouseEntered
        // TODO add your handling code here:
        btntransaksibaru.setBackground(new Color(156,195,223));
    }//GEN-LAST:event_btntransaksibaruMouseEntered

    private void btntransaksibaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransaksibaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntransaksibaruActionPerformed

    private void btnpesananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesananMouseEntered
        // TODO add your handling code here:
        btnpesanan.setBackground(new Color(156,195,223));
    }//GEN-LAST:event_btnpesananMouseEntered

    private void btnpesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesananActionPerformed
        // TODO add your handling code here:
        btntransaksibaru.setBackground(new Color(156,195,223));
    }//GEN-LAST:event_btnpesananActionPerformed

    private void btntransaksibaruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransaksibaruMouseExited
        // TODO add your handling code here:
        btntransaksibaru.setBackground(new Color(217,217,217));
    }//GEN-LAST:event_btntransaksibaruMouseExited

    private void btnpesananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesananMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpesananMouseExited

    private void btnriwayatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnriwayatMouseExited
        // TODO add your handling code here:
        btnriwayat.setBackground(new Color(217,217,217));
    }//GEN-LAST:event_btnriwayatMouseExited

    private void btntransaksibaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntransaksibaruMouseClicked
        // TODO add your handling code here:
        new transaksibaru().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btntransaksibaruMouseClicked

    private void btnriwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnriwayatMouseClicked
        // TODO add your handling code here:
        btnriwayat.setBackground(new Color(156,195,223));
        new riwayat().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnriwayatMouseClicked

    private void jeniscucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeniscucianActionPerformed
        // TODO add your handling code here:
        if (jeniscucian.getSelectedItem().toString().equalsIgnoreCase("cuci basah")){
            txtharga.setText("3000");     
        } else if (jeniscucian.getSelectedItem().toString().equalsIgnoreCase("cuci kering")){
            txtharga.setText("4000");
        } else if (jeniscucian.getSelectedItem().toString().equalsIgnoreCase("cuci setrika")){
            txtharga.setText("5000");
        }
    }//GEN-LAST:event_jeniscucianActionPerformed

    private void txtberatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtberatKeyReleased
        // TODO add your handling code here:
        int harga = Integer.parseInt(txtharga.getText());
        int berat = Integer.parseInt(txtberat.getText());
        int totalbayar = harga*berat;
        String total = Integer.toString(totalbayar);
        txttotal.setText(total);
        
    }//GEN-LAST:event_txtberatKeyReleased

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        jeniscucian.setSelectedItem("pilih");
        txtharga.setText("");
        txtberat.setText("");
        txttotal.setText("");
        txtbayar.setText("");
        new menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btntransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransaksiActionPerformed
        // TODO add your handling code here:
        
        if (jeniscucian.getSelectedItem()== "Pilih"||txtharga.getText().isEmpty()||txtberat.getText().isEmpty()||txttotal.getText().isEmpty()||txtbayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Lengkapi From Terlebih Dahulu");
        }else {
            JOptionPane.showMessageDialog(null, "Transaksi");
            int bayar = Integer.parseInt(txtbayar.getText());
            int totalharga = Integer.parseInt(txttotal.getText());
            int kembalian = bayar - totalharga;
            String kembali = Integer.toString(kembalian);
            JOptionPane.showMessageDialog(null, "kembalian anda : \n" + kembali);
            
        
        }
       
    }//GEN-LAST:event_btntransaksiActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here
        String nama_pelanggan ,jenis_cucian,harga,berat,total_harga,bayar, query;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/laundry_user";
        SUser = "root";
        SPass = "";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            
            nama_pelanggan = String.valueOf(cmbpelanggan.getSelectedItem());
            jenis_cucian = String.valueOf(jeniscucian.getSelectedItem());
            harga = txtharga.getText();
            berat = txtberat.getText();
            total_harga = txttotal.getText();
            bayar = txtbayar.getText();
            
            query = "INSERT INTO transaksi(nama_pelanggan, jenis_cucian, harga, berat, total_harga, bayar)" + "VALUES ('"+nama_pelanggan+"','"+jenis_cucian+"','"+harga+"','"+berat+"','"+total_harga+"','"+bayar+"')";
                                
                st.execute(query);
                cmbpelanggan.setSelectedItem("");
                jeniscucian.setSelectedItem("");
                txtharga.setText("");
                txtberat.setText("");
                txttotal.setText("");
                txtbayar.setText("");
                
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
                new riwayat().setVisible(true);
                this.dispose();
            }     
        catch(Exception e){
            System.out.println("Error!" + e.getMessage());
        }
            
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void cmbpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpelangganActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmbpelangganActionPerformed

    private void btndatapelngganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatapelngganActionPerformed
        // TODO add your handling code here:
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/laundry_user";
        SUser = "root";
        SPass = "";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            String sql = "select * from pelanggan";
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()){
                cmbpelanggan.addItem(rs.getString("nama_pelanggan"));
        }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_btndatapelngganActionPerformed

    private void txtberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberatActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btndatapelnggan;
    private javax.swing.JButton btnpesanan;
    private javax.swing.JButton btnriwayat;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntransaksi;
    private javax.swing.JButton btntransaksibaru;
    private javax.swing.JComboBox<String> cmbpelanggan;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jeniscucian;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    void setUser(String nama) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String rsgetString(String nama_pelanggan) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
